stages:
  data_ingestion:
    cmd: python src/CNNclassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/CNNclassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/CT-scan_kidney_normal_tumor_images
 
  prepare_base_model:
    cmd: python src/CNNclassifier/pipeline/stage_2_prepare_base_model.py
    deps:
      - src/CNNclassifier/pipeline/stage_2_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src\CNNclassifier\pipeline\stage_3_model_training.py
    deps:
      - src\CNNclassifier\pipeline\stage_3_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/CT-scan_kidney_normal_tumor_images
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  evaluation:
    cmd: python src/CNNclassifier/pipeline/stage_04_model_evaluation.py
    deps:
      - src/CNNclassifier/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/CT-scan_kidney_normal_tumor_images
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false